title: Towerslag one more time
author: Valmont Layne
email: valmont.layne@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
# social links
twitter_username: Layntjie # DO NOT include the @ character, or else the build will fail!
github_username:  Layntjie # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

